In [1]:
import pandas as pd

In [2]:
roll = pd.Series([1, 2, 3, 4, 5])
name = pd.Series(['Sia', 'Ravi', 'Geet', 'Ajinkya', 'Avinash'])
marks= pd.Series([85, 67, 59, 40, 90])

In [3]:
df = pd.DataFrame({
    'Id':roll,
    'Name':name,
    'Marks':marks
})

In [4]:
df

   Id     Name  Marks
0   1      Sia     85
1   2     Ravi     67
2   3     Geet     59
3   4  Ajinkya     40
4   5  Avinash     90

In [5]:
df.values

array([[1, 'Sia', 85],
       [2, 'Ravi', 67],
       [3, 'Geet', 59],
       [4, 'Ajinkya', 40],
       [5, 'Avinash', 90]], dtype=object)

In [6]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [7]:
df.shape

(5, 3)

In [8]:
df.ndim

2

In [9]:
df.size

15

In [10]:
df.columns

Index(['Id', 'Name', 'Marks'], dtype='object')

In [11]:
"""

url -> https://mitu.co.in/dataset

download all the dataset starting with student*
put them in the same file folder as your current working directory

""";

In [12]:
pwd

'C:\\Users\\Aarti  Gaikwad'

In [13]:
df = pd.read_csv("student.csv")

In [14]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [15]:
df.shape

(10, 5)

In [16]:
df.columns

Index(['roll', 'name', 'class', 'marks', 'age'], dtype='object')

In [17]:
# student1.csv

In [18]:
df = pd.read_csv("student1.csv")

In [19]:
df

    1     anil  TE  56.77  22
0   2     amit  TE  59.77  21
1   3   aniket  BE  76.88  19
2   4  ajinkya  TE  69.66  20
3   5     asha  TE  63.28  20
4   6   ayesha  BE  49.55  20
5   7     amar  BE  65.34  19
6   8    amita  BE  68.33  23
7   9     amol  TE  56.75  20
8  10    anmol  BE  78.66  21

In [20]:
df.shape

(9, 5)

In [21]:
df.columns

Index(['1', 'anil', 'TE', '56.77', '22'], dtype='object')

In [22]:
col = ['roll', 'name', 'class', 'marks', 'age']

In [23]:
df = pd.read_csv('student1.csv', names=col)
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [24]:
# student3.tsv

In [27]:
df = pd.read_csv('student3.tsv')

In [28]:
df

  roll\tname\tclass\tmarks\tage
0        1\tanil\tTE\t56.77\t22
1        2\tamit\tTE\t59.77\t21
2      3\taniket\tBE\t76.88\t19
3     4\tajinkya\tTE\t69.66\t20
4        5\tasha\tTE\t63.28\t20
5      6\tayesha\tBE\t49.55\t20
6        7\tamar\tBE\t65.34\t19
7       8\tamita\tBE\t68.33\t23
8        9\tamol\tTE\t56.75\t20
9      10\tanmol\tBE\t78.66\t21

In [29]:
df = pd.read_csv('student3.tsv', sep = '\t')

In [30]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21