In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('student.csv')

In [3]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [4]:
df.shape

(10, 5)

In [5]:
df.columns

Index(['roll', 'name', 'class', 'marks', 'age'], dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   roll    10 non-null     int64
 1   name    10 non-null     object
 2   class   10 non-null     object
 3   marks   10 non-null     float64
 4   age     10 non-null     int64
dtypes: float64(1), int64(2), object(2)
memory usage: 532.0+ bytes

In [7]:
df.head()

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20

In [8]:
df.head(7)

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19

In [9]:
df.head(10)

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [10]:
df.tail()

   roll    name class  marks  age
5     6  ayesha    BE  49.55   20
6     7    amar    BE  65.34   19
7     8   amita    BE  68.33   23
8     9    amol    TE  56.75   20
9    10   anmol    BE  78.66   21

In [11]:
df.tail(3)

   roll   name class  marks  age
7     8  amita    BE  68.33   23
8     9   amol    TE  56.75   20
9    10  anmol    BE  78.66   21

In [12]:
df.values

array([[1, 'anil', 'TE', 56.77, 22],
       [2, 'amit', 'TE', 59.77, 21],
       [3, 'aniket', 'BE', 76.88, 19],
       [4, 'ajinkya', 'TE', 69.66, 20],
       [5, 'asha', 'TE', 63.28, 20],
       [6, 'ayesha', 'BE', 49.55, 20],
       [7, 'amar', 'BE', 65.34, 19],
       [8, 'amita', 'BE', 68.33, 23],
       [9, 'amol', 'TE', 56.75, 20],
       [10, 'anmol', 'BE', 78.66, 21]], dtype=object)

In [13]:
df.T

,0,1,2,3,4,5,6,7,8,9
roll,1,2,3,4,5,6,7,8,9,10
name,anil,amit,aniket,ajinkya,asha,ayesha,amar,amita,amol,anmol
class,TE,TE,BE,TE,TE,BE,BE,BE,TE,BE
marks,56.77,59.77,76.88,69.66,63.28,49.55,65.34,68.33,56.75,78.66
age,22,21,19,20,20,20,19,23,20,21

In [14]:
# Slicing

In [15]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [16]:
df.iloc[1:4]

   roll     name class  marks  age
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20

In [17]:
# Another way
df[1:4]

   roll     name class  marks  age
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20

In [18]:
df.iloc[1:4, 1:4]

      name class  marks
1     amit    TE  59.77
2   aniket    BE  76.88
3  ajinkya    TE  69.66

In [19]:
df.iloc[1:5, [0,1,3]]

   roll     name  marks
1     2     amit  59.77
2     3   aniket  76.88
3     4  ajinkya  69.66
4     5     asha  63.28

In [20]:
df.iloc[[1,2,3,4,6], [0,1,3]]

   roll     name  marks
1     2     amit  59.77
2     3   aniket  76.88
3     4  ajinkya  69.66
4     5     asha  63.28
6     7     amar  65.34

In [21]:
df.iloc[5, 1] = "geet"

In [22]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6     geet    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [23]:
# Loc

In [24]:
df.loc[2:5, 'name']

2     aniket
3    ajinkya
4       asha
5       geet
Name: name, dtype: object

In [25]:
df.loc[2:5, ['name', 'class']]

      name class
2   aniket    BE
3  ajinkya    TE
4     asha    TE
5     geet    BE

In [26]:
df.loc[0:9, 'name']

0       anil
1       amit
2     aniket
3    ajinkya
4       asha
5       geet
6       amar
7      amita
8       amol
9      anmol
Name: name, dtype: object

In [27]:
# Another way
df.loc[:, 'name']

0       anil
1       amit
2     aniket
3    ajinkya
4       asha
5       geet
6       amar
7      amita
8       amol
9      anmol
Name: name, dtype: object

In [28]:
# Another way
df['name']

0       anil
1       amit
2     aniket
3    ajinkya
4       asha
5       geet
6       amar
7      amita
8       amol
9      anmol
Name: name, dtype: object

In [29]:
df[['name', 'class']]

      name class
0     anil    TE
1     amit    TE
2   aniket    BE
3  ajinkya    TE
4     asha    TE
5     geet    BE
6     amar    BE
7    amita    BE
8     amol    TE
9    anmol    BE

In [30]:
df['name'].str.upper()

0       ANIL
1       AMIT
2     ANIKET
3    AJINKYA
4       ASHA
5       GEET
6       AMAR
7      AMITA
8       AMOL
9      ANMOL
Name: name, dtype: object

In [31]:
# Add or modify the columns

In [32]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6     geet    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [39]:
gender = ['m', 'm', 'm', 'm', 'f', 'm', 'm', 'f', 'm', 'm']

In [40]:

df['gender'] = gender

In [41]:
df

   roll     name class  marks  age gender
0   201     anil    TE  56.77   22      m
1   202     amit    TE  59.77   21      m
2   203   aniket    BE  76.88   19      m
3   204  ajinkya    TE  69.66   20      m
4   205     asha    TE  63.28   20      f
5   206     geet    BE  49.55   20      m
6   207     amar    BE  65.34   19      m
7   208    amita    BE  68.33   23      f
8   209     amol    TE  56.75   20      m
9   210    anmol    BE  78.66   21      m

In [42]:
df['roll'] = df['roll'] + 100

In [43]:
df

   roll     name class  marks  age gender
0   301     anil    TE  56.77   22      m
1   302     amit    TE  59.77   21      m
2   303   aniket    BE  76.88   19      m
3   304  ajinkya    TE  69.66   20      m
4   305     asha    TE  63.28   20      f
5   306     geet    BE  49.55   20      m
6   307     amar    BE  65.34   19      m
7   308    amita    BE  68.33   23      f
8   309     amol    TE  56.75   20      m
9   310    anmol    BE  78.66   21      m

In [44]:
# Add a new column cgpa
# Values should => marks/10 + 1.5

In [45]:
df['cgpa'] = df['marks']/10 + 1.5

In [46]:
df

   roll     name class  marks  age gender   cgpa
0   301     anil    TE  56.77   22      m  7.177
1   302     amit    TE  59.77   21      m  7.477
2   303   aniket    BE  76.88   19      m  9.188
3   304  ajinkya    TE  69.66   20      m  8.466
4   305     asha    TE  63.28   20      f  7.828
5   306     geet    BE  49.55   20      m  6.455
6   307     amar    BE  65.34   19      m  8.034
7   308    amita    BE  68.33   23      f  8.333
8   309     amol    TE  56.75   20      m  7.175
9   310    anmol    BE  78.66   21      m  9.366

In [47]:
df.sort_values(by= 'name')

   roll     name class  marks  age gender   cgpa
3   304  ajinkya    TE  69.66   20      m  8.466
6   307     amar    BE  65.34   19      m  8.034
1   302     amit    TE  59.77   21      m  7.477
7   308    amita    BE  68.33   23      f  8.333
8   309     amol    TE  56.75   20      m  7.175
2   303   aniket    BE  76.88   19      m  9.188
0   301     anil    TE  56.77   22      m  7.177
9   310    anmol    BE  78.66   21      m  9.366
4   305     asha    TE  63.28   20      f  7.828
5   306     geet    BE  49.55   20      m  6.455

In [48]:
df

   roll     name class  marks  age gender   cgpa
0   301     anil    TE  56.77   22      m  7.177
1   302     amit    TE  59.77   21      m  7.477
2   303   aniket    BE  76.88   19      m  9.188
3   304  ajinkya    TE  69.66   20      m  8.466
4   305     asha    TE  63.28   20      f  7.828
5   306     geet    BE  49.55   20      m  6.455
6   307     amar    BE  65.34   19      m  8.034
7   308    amita    BE  68.33   23      f  8.333
8   309     amol    TE  56.75   20      m  7.175
9   310    anmol    BE  78.66   21      m  9.366

In [49]:
# Sort by class and then marks simultaneously and check the result

In [50]:
df.sort_values(by=['class', 'marks'])

   roll     name class  marks  age gender   cgpa
5   306     geet    BE  49.55   20      m  6.455
6   307     amar    BE  65.34   19      m  8.034
7   308    amita    BE  68.33   23      f  8.333
2   303   aniket    BE  76.88   19      m  9.188
9   310    anmol    BE  78.66   21      m  9.366
8   309     amol    TE  56.75   20      m  7.175
0   301     anil    TE  56.77   22      m  7.177
1   302     amit    TE  59.77   21      m  7.477
4   305     asha    TE  63.28   20      f  7.828
3   304  ajinkya    TE  69.66   20      m  8.466

In [51]:
df['marks'].mean()

np.float64(64.499)

In [52]:
df['marks'].max()

78.66

In [53]:
df.describe()

            roll      marks        age       cgpa
count   10.00000  10.000000  10.000000  10.000000
mean   305.50000  64.499000  20.500000   7.949900
std      3.02765   9.207179   1.269296   0.920718
min    301.00000  49.550000  19.000000   6.455000
25%    303.25000  57.520000  20.000000   7.252000
50%    305.50000  64.310000  20.000000   7.931000
75%    307.75000  69.327500  21.000000   8.432750
max    310.00000  78.660000  23.000000   9.366000

In [55]:
# Groupby

In [56]:
gr = df.groupby('class')

In [57]:
gr.groups

{'BE': [2, 5, 6, 7, 9], 'TE': [0, 1, 3, 4, 8]}

In [59]:
gr.get_group('BE')

   roll    name class  marks  age gender   cgpa
2   303  aniket    BE  76.88   19      m  9.188
5   306    geet    BE  49.55   20      m  6.455
6   307    amar    BE  65.34   19      m  8.034
7   308   amita    BE  68.33   23      f  8.333
9   310   anmol    BE  78.66   21      m  9.366

In [60]:
gr.min()

       roll     name  marks  age gender   cgpa
class
BE      303     amar  49.55   19      f  6.455
TE      301  ajinkya  56.75   20      f  7.175

In [61]:
gr['marks'].mean()

class
BE    67.752
TE    61.246
Name: marks, dtype: float64

In [62]:
# Boolean filtering

In [63]:
df

   roll     name class  marks  age gender   cgpa
0   301     anil    TE  56.77   22      m  7.177
1   302     amit    TE  59.77   21      m  7.477
2   303   aniket    BE  76.88   19      m  9.188
3   304  ajinkya    TE  69.66   20      m  8.466
4   305     asha    TE  63.28   20      f  7.828
5   306     geet    BE  49.55   20      m  6.455
6   307     amar    BE  65.34   19      m  8.034
7   308    amita    BE  68.33   23      f  8.333
8   309     amol    TE  56.75   20      m  7.175
9   310    anmol    BE  78.66   21      m  9.366

In [64]:
df['marks'] > 60

0    False
1    False
2     True
3     True
4     True
5    False
6     True
7     True
8    False
9     True
Name: marks, dtype: bool

In [65]:
df[df['marks'] > 60]

   roll     name class  marks  age gender   cgpa
2   303   aniket    BE  76.88   19      m  9.188
3   304  ajinkya    TE  69.66   20      m  8.466
4   305     asha    TE  63.28   20      f  7.828
6   307     amar    BE  65.34   19      m  8.034
7   308    amita    BE  68.33   23      f  8.333
9   310    anmol    BE  78.66   21      m  9.366

In [66]:
# Filter the data of those student -> marks > 60 and belong to BE class

In [67]:
f = df[(df['marks'] > 60) & (df['class'] == 'BE')]

In [68]:
f

   roll    name class  marks  age gender   cgpa
2   303  aniket    BE  76.88   19      m  9.188
6   307    amar    BE  65.34   19      m  8.034
7   308   amita    BE  68.33   23      f  8.333
9   310   anmol    BE  78.66   21      m  9.366

In [69]:
# Drop -> drop columns or rows

In [70]:
df

   roll     name class  marks  age gender   cgpa
0   301     anil    TE  56.77   22      m  7.177
1   302     amit    TE  59.77   21      m  7.477
2   303   aniket    BE  76.88   19      m  9.188
3   304  ajinkya    TE  69.66   20      m  8.466
4   305     asha    TE  63.28   20      f  7.828
5   306     geet    BE  49.55   20      m  6.455
6   307     amar    BE  65.34   19      m  8.034
7   308    amita    BE  68.33   23      f  8.333
8   309     amol    TE  56.75   20      m  7.175
9   310    anmol    BE  78.66   21      m  9.366

In [71]:
df.drop(4)

   roll     name class  marks  age gender   cgpa
0   301     anil    TE  56.77   22      m  7.177
1   302     amit    TE  59.77   21      m  7.477
2   303   aniket    BE  76.88   19      m  9.188
3   304  ajinkya    TE  69.66   20      m  8.466
5   306     geet    BE  49.55   20      m  6.455
6   307     amar    BE  65.34   19      m  8.034
7   308    amita    BE  68.33   23      f  8.333
8   309     amol    TE  56.75   20      m  7.175
9   310    anmol    BE  78.66   21      m  9.366

In [72]:
df.drop([4, 5, 6])

   roll     name class  marks  age gender   cgpa
0   301     anil    TE  56.77   22      m  7.177
1   302     amit    TE  59.77   21      m  7.477
2   303   aniket    BE  76.88   19      m  9.188
3   304  ajinkya    TE  69.66   20      m  8.466
7   308    amita    BE  68.33   23      f  8.333
8   309     amol    TE  56.75   20      m  7.175
9   310    anmol    BE  78.66   21      m  9.366

In [73]:
# Drop name column

In [74]:
df.drop('name', axis = 1)

   roll class  marks  age gender   cgpa
0   301    TE  56.77   22      m  7.177
1   302    TE  59.77   21      m  7.477
2   303    BE  76.88   19      m  9.188
3   304    TE  69.66   20      m  8.466
4   305    TE  63.28   20      f  7.828
5   306    BE  49.55   20      m  6.455
6   307    BE  65.34   19      m  8.034
7   308    BE  68.33   23      f  8.333
8   309    TE  56.75   20      m  7.175
9   310    BE  78.66   21      m  9.366

In [75]:
# Drop name and class

In [76]:
df. drop(['name','class'],axis = 1)

   roll  marks  age gender   cgpa
0   301  56.77   22      m  7.177
1   302  59.77   21      m  7.477
2   303  76.88   19      m  9.188
3   304  69.66   20      m  8.466
4   305  63.28   20      f  7.828
5   306  49.55   20      m  6.455
6   307  65.34   19      m  8.034
7   308  68.33   23      f  8.333
8   309  56.75   20      m  7.175
9   310  78.66   21      m  9.366

In [77]:
df

   roll     name class  marks  age gender   cgpa
0   301     anil    TE  56.77   22      m  7.177
1   302     amit    TE  59.77   21      m  7.477
2   303   aniket    BE  76.88   19      m  9.188
3   304  ajinkya    TE  69.66   20      m  8.466
4   305     asha    TE  63.28   20      f  7.828
5   306     geet    BE  49.55   20      m  6.455
6   307     amar    BE  65.34   19      m  8.034
7   308    amita    BE  68.33   23      f  8.333
8   309     amol    TE  56.75   20      m  7.175
9   310    anmol    BE  78.66   21      m  9.366

In [78]:
df.drop(['gender', 'cgpa'], axis = 1, inplace = True)

In [80]:
df
# create a dataframe newdf
# columns -> roll, gender, cgpa
# roll column will have the same values as that of in the df dataframe

   roll     name class  marks  age
0   301     anil    TE  56.77   22
1   302     amit    TE  59.77   21
2   303   aniket    BE  76.88   19
3   304  ajinkya    TE  69.66   20
4   305     asha    TE  63.28   20
5   306     geet    BE  49.55   20
6   307     amar    BE  65.34   19
7   308    amita    BE  68.33   23
8   309     amol    TE  56.75   20
9   310    anmol    BE  78.66   21

In [81]:
newdf = pd.DataFrame({
    'roll': df['roll'],
    'gender': gender,
    'cgpa': df['marks']/10 + 1.5
})
newdf

   roll gender   cgpa
0   301      m  7.177
1   302      m  7.477
2   303      m  9.188
3   304      m  8.466
4   305      f  7.828
5   306      m  6.455
6   307      m  8.034
7   308      f  8.333
8   309      m  7.175
9   310      m  9.366

In [83]:
pd.merge(df, newdf)

   roll     name class  marks  age gender   cgpa
0   301     anil    TE  56.77   22      m  7.177
1   302     amit    TE  59.77   21      m  7.477
2   303   aniket    BE  76.88   19      m  9.188
3   304  ajinkya    TE  69.66   20      m  8.466
4   305     asha    TE  63.28   20      f  7.828
5   306     geet    BE  49.55   20      m  6.455
6   307     amar    BE  65.34   19      m  8.034
7   308    amita    BE  68.33   23      f  8.333
8   309     amol    TE  56.75   20      m  7.175
9   310    anmol    BE  78.66   21      m  9.366

In [86]:
# Concat

In [87]:
# load student5.csv

In [88]:
newdf = pd.read_csv('student5.csv')
newdf

   roll     name class  marks  age
0     1   surbhi    TE  67.44   23
1     2    sujay    TE  74.12   22
2     3  subhash    BE  82.44   21
3     4   sachin    TE  59.33   21
4     5  shalini    TE  63.45   20

In [89]:
pd.concat([df, newdf], ignore_index= True)

    roll     name class  marks  age
0    301     anil    TE  56.77   22
1    302     amit    TE  59.77   21
2    303   aniket    BE  76.88   19
3    304  ajinkya    TE  69.66   20
4    305     asha    TE  63.28   20
5    306     geet    BE  49.55   20
6    307     amar    BE  65.34   19
7    308    amita    BE  68.33   23
8    309     amol    TE  56.75   20
9    310    anmol    BE  78.66   21
10     1   surbhi    TE  67.44   23
11     2    sujay    TE  74.12   22
12     3  subhash    BE  82.44   21
13     4   sachin    TE  59.33   21
14     5  shalini    TE  63.45   20

In [90]:
f = df[(df['marks'] > 60) & (df['class'] == 'BE')]